### PR TITLE
Add «Using Node.js» section in Hosting docs

### PR DESCRIPTION
**Pull request by yuchi**
Probably the style is not exactly yours, @zenorocha, but I tried to be as simple as possible.

I used Gulp as the target tool in the examples, but it could work also as a vanilla JS script (this is the first time I used “script” in relation to a JS file in years).

### CODE REVIEW

**Comment by zenorocha** [comment]
Hey @yuchi,

Thanks a lot! I think we'll need to hold this for now, here's why: hosting is a very generic service, it doesn't depend on any back-end language, if we do that we'd have to create guides for tools made with Java, Python, and other technologies as well.

But don't feel discouraged, I loved this explanation and I think it will suit better as a blog post once we have the WeDeploy blog setup.

Is that ok with you?

**Comment by eduardolundgren** [comment]
We definitely need to move this to a blog post! Thanks @yuchi

**Comment by yuchi** [comment]
Once you have that in place just drop me a line. I'll be honored to be a guest author 👌

**Comment by zenorocha** [comment]
> Closing until we land a new blog for this article :)

**Pull request closed without merging**
